export { SVGhome, SVGsearch, SVGwatchlist, SVGoriginals, SVGmovies, SVGseries, SVGgroupWatch, SVGplay, SVGcheckbox } from './svg';
export { ButtonLoginV1, ButtonSignUpV1, ButtonSignUpV2 } from './buttons';

export { AgreementES } from './agreement';
export { default as Brand } from './brand';
export { default as Features } from './features';
export { default as Footer } from './footer';
export { default as Gadget } from './gadget';
export { default as Header } from './header';
export { default as Hero } from './hero';
export { default as HeroEN } from './heroEN';
export { default as Login } from './login';
export { default as Logo } from './logo';
export { default as Productions } from './productions';
export { default as Promotion } from './promotion';
export { default as ScrollToTop } from './scrolltotop';
export { default as Section } from './section';
export { default as Site } from './site';
export { default as Spinner } from './spinner';
export { default as Wrapper } from './wrapper';
export { default as Collection } from './collection';
export { default as Media } from './media';
export { default as Detail } from './detail';
export { default as Season } from './season';
export { default as Signup } from './signup';
export { default as Modal } from './modal';
export { default as NoMatch } from './nomatch';
